//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPassBank.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passwords
    {
        public int AccountId { get; set; }
        public byte[] KeyWord { get; set; }
        public byte[] Description { get; set; }
        public byte[] Login { get; set; }
        public byte[] Password { get; set; }
        public int Id { get; set; }
    }
}
